version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:

    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
#      - ./db/:/my/sqlite/path/

    depends_on:
      - db
volumes:
  postgres_data: