"""empty message

Revision ID: 59490f6f779a
Revises: 7847eba97e5b
Create Date: 2023-12-14 14:40:01.793506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59490f6f779a'
down_revision = '7847eba97e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
